### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by goncalorazevedo** [diogotcorreia/proj-ist-unit-tests#98]
I believe it would be clearer if each project would use civil year convention, i.e po/2021 instead of po/2021-2022 as it would make the repo more "readable" and it's clear enough that 2021 refers to 2021-2022 even if the course happens to go into the next year (for example, 1st semester courses of the 2nd period, so/2021 is still clear what it refers to). Even though 2nd semester classes would appear to be of "different years" it would not cause any conflicts for future people because courses are lectured always 1 year apart and every student will always know that 2022 IAED project refers to the 2021-2022 semester. This might seem kinda picky, let me know!

**Comment by diogotcorreia** [comment]
I also agree having `2021-2022` is quite annoying and unreadable at times.
However, it's explicit what everything is. Having `lp/2022`, for example, you wouldn't know if it is this year's or last year's (because LP is lectured November - February). You said it's clear enough for people to know what it refers to because of context and commit history (it shows right there the last change, it's probably easy to infer from that), but it might still cause confusion.

I'm in favor of keeping it as is, but I'm open to more opinions.

Other options that came to my head are things like `22-23` or even `2223`, but those might be even more confusing.

@RafDevX @Pesteves2002

**Comment by Pesteves2002** [comment]
I really prefer the way it is now tbh.
But if we were to change i think `22-23` would be the way to go.
